USE DB52;
CREATE TABLE Post (
Post_ID VARCHAR(20) NOT NULL PRIMARY KEY,
Title VARCHAR(20),
Reviews NUMERIC(1,1),
Difficulty_Level INT,
Recipe_Cost VARCHAR(3),
Content VARCHAR(800),
Recipe_Category VARCHAR(20),
Recipe_Time TIME,
Status INT,
)

CREATE TABLE Comment (
Comment_ID VARCHAR(20) NOT NULL PRIMARY KEY,
C_Content VARCHAR(30),
C_Sender VARCHAR(20) NOT NULL,
C_Receiver VARCHAR(20) NOT NULL,
)

CREATE TABLE Messages (
ID_Message VARCHAR(20) NOT NULL PRIMARY KEY,
M_Content VARCHAR(500),
M_Time TIME,
M_Date DATE,
M_Sender VARCHAR(20) NOT NULL,
M_Receiver VARCHAR(20) NOT NULL,
)

CREATE TABLE [User] (
ID VARCHAR(10) NOT NULL PRIMARY KEY,
Password VARCHAR(20) NOT NULL,
Username VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Bio VARCHAR(50),
Post_ID VARCHAR(20) NOT NULL,
Comment_ID VARCHAR(20) NOT NULL,
ID_Message VARCHAR(20) NOT NULL,
CONSTRAINT FK_User_Post FOREIGN KEY(Post_ID) REFERENCES Post,
CONSTRAINT FK_User_Comment FOREIGN KEY(Comment_ID) REFERENCES Comment,
CONSTRAINT FK_User_Messages FOREIGN KEY(ID_Message) REFERENCES Messages,
)





