USE DB52;

CREATE TABLE [User] (
ID VARCHAR(10) NOT NULL PRIMARY KEY,
Password VARCHAR(20) NOT NULL,
Username VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Bio VARCHAR(50),
)

CREATE TABLE Post (
PostID VARCHAR(20) NOT NULL PRIMARY KEY,
PostStatus INT,
RecipeTime TIME,
Content VARCHAR(800) NOT NULL,
Title VARCHAR(20) NOT NULL,
RecipeCategory VARCHAR(20),
DifficultyLevel VARCHAR(20),
RecipeCost VARCHAR(5),
Reviews INT,
Creator VARCHAR(10) NOT NULL,
CONSTRAINT FK_Post_User FOREIGN KEY(Creator) REFERENCES [User](ID)
)

CREATE TABLE Comment (
CommentID VARCHAR(20) NOT NULL PRIMARY KEY,
Content VARCHAR(30) NOT NULL,
Sender VARCHAR(10) NOT NULL,
ToPost VARCHAR(20) NOT NULL,
Receiver VARCHAR(10),
CONSTRAINT FK_Comment_User_1 FOREIGN KEY(Sender) REFERENCES [User](ID),
CONSTRAINT FK_Comment_User_2 FOREIGN KEY(Receiver) REFERENCES [User](ID),
CONSTRAINT FK_Comment_Post FOREIGN KEY(ToPost) REFERENCES Post(PostID)
)

CREATE TABLE Messages (
MessageID VARCHAR(20) NOT NULL PRIMARY KEY,
Content VARCHAR(500) NOT NULL,
Time TIME NOT NULL,
Date DATE NOT NULL,
Sender VARCHAR(10) NOT NULL,
Receiver VARCHAR(10) NOT NULL,
CONSTRAINT FK_Messages_User_1 FOREIGN KEY(Sender) REFERENCES [User](ID),
CONSTRAINT FK_Messages_User_2 FOREIGN KEY(Receiver) REFERENCES [User](ID)
)

CREATE TABLE Cookmates (
UserID VARCHAR(10) NOT NULL,
CookmateID VARCHAR(10) NOT NULL,
CONSTRAINT FK_Cookmates_User_1 FOREIGN KEY(UserID) REFERENCES [User](ID),
CONSTRAINT FK_Cookmates_User_2 FOREIGN KEY(CookmateID) REFERENCES [User](ID),
CONSTRAINT PK_Cookmates PRIMARY KEY(UserID, CookmateID)
)
